[build-system]
requires = ["setuptools>=51"]
build-backend = "setuptools.build_meta"

[tool.mypy]
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = [
    "h5py.*",
    "matplotlib.*",
    "scipy.*",
]
ignore_missing_imports = true
